server:
  port: 7777
  
management:
  security:
    enabled: false
                
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
  profiles:
     active: native
